import React from 'react';
import { Download, FileText, Loader2 } from 'lucide-react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

interface Question {
  id?: string;
  question_id?: string;
  question?: string;
  question_text?: string;
  options?: string[];
  correctAnswer?: string;
  correct_answer?: string;
  solution?: string;
  explanation?: string;
  year?: string;
  pyqYear?: string;
  exam?: string;
  subject?: string;
}

interface QuestionExporterProps {
  questions: Question[];
  title: string;
  className?: string;
}

export const QuestionExporter: React.FC<QuestionExporterProps> = ({ questions, title, className }) => {
  const [isExporting, setIsExporting] = React.useState(false);

  const exportToPDF = async () => {
    setIsExporting(true);
    try {
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 10; // Reduced margin to use more of the page
      let y = 20;

      const addHeader = (pageNum: number) => {
        // Header Background
        doc.setFillColor(15, 23, 42); // Dark slate
        doc.rect(0, 0, pageWidth, 20, 'F');
        
        // Logo Text
        doc.setFontSize(16);
        doc.setTextColor(0, 240, 255); // #00F0FF
        doc.setFont('helvetica', 'bold');
        doc.text('SMART SUNRISE', margin, 13);
        
        // Tagline
        doc.setFontSize(7);
        doc.setTextColor(176, 38, 255); // #B026FF
        doc.text('AI-POWERED EDUCATIONAL ENGINE', margin + 50, 13);

        // Page Number
        doc.setFontSize(8);
        doc.setTextColor(200, 200, 200);
        doc.text(`Page ${pageNum}`, pageWidth - margin, 13, { align: 'right' });
      };

      const addFooter = () => {
        doc.setFontSize(7);
        doc.setTextColor(150, 150, 150);
        doc.text('© 2026 Smart Sunrise. Generated by AI Assistant. For educational purposes only.', pageWidth / 2, pageHeight - 8, { align: 'center' });
      };

      addHeader(1);
      y = 30;

      // Document Title
      doc.setFontSize(24);
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      const titleLines = doc.splitTextToSize(title.toUpperCase(), pageWidth - 2 * margin);
      doc.text(titleLines, margin, y);
      y += titleLines.length * 10 + 5;

      // Subheading / Metadata
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.setFont('helvetica', 'normal');
      doc.text(`Total Questions: ${questions.length} | Generated on ${new Date().toLocaleDateString()}`, margin, y);
      
      // Horizontal Line
      y += 5;
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, y, pageWidth - margin, y);
      y += 12;

      let currentPage = 1;
      const answers: { index: number; answer: string }[] = [];

      for (let i = 0; i < questions.length; i++) {
        const q = questions[i];
        const questionText = q.question || q.question_text || '';
        const correctAnswer = q.correctAnswer || q.correct_answer || '';
        const solutionText = q.solution || q.explanation || '';
        const yearText = q.year || q.pyqYear || '';
        
        if (correctAnswer) {
          answers.push({ index: i + 1, answer: correctAnswer });
        }

        // Calculate Question Height
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        const questionLines = doc.splitTextToSize(`Q${i + 1}. ${questionText}`, pageWidth - 2 * margin - 5);
        const questionHeight = questionLines.length * 6;

        // Calculate Options Height
        let optionsHeight = 0;
        const optionsLines: string[][] = [];
        if (q.options && q.options.length > 0) {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          q.options.forEach((opt, idx) => {
            const label = String.fromCharCode(65 + idx) + ') ';
            const optLines = doc.splitTextToSize(`${label}${opt}`, pageWidth - 2 * margin - 12);
            optionsLines.push(optLines);
            optionsHeight += optLines.length * 5 + 2;
          });
        }

        // Calculate Solution Height
        let solutionHeight = 0;
        let solutionLines: string[] = [];
        if (solutionText) {
          doc.setFontSize(9);
          doc.setFont('helvetica', 'italic');
          solutionLines = doc.splitTextToSize(`Explanation: ${solutionText}`, pageWidth - 2 * margin - 10);
          solutionHeight = solutionLines.length * 4.5 + 6;
        }
        
        const metadataHeight = (yearText || q.exam || q.subject) ? 8 : 0;
        const totalHeight = questionHeight + optionsHeight + solutionHeight + metadataHeight + 10;

        // Page break check
        if (y + totalHeight > pageHeight - 20) {
          doc.addPage();
          currentPage++;
          addHeader(currentPage);
          y = 30;
        }

        // Question Box
        doc.setFillColor(252, 252, 253);
        doc.setDrawColor(241, 245, 249);
        doc.roundedRect(margin - 2, y - 5, pageWidth - 2 * margin + 4, totalHeight, 2, 2, 'FD');

        // Draw Question
        doc.setFontSize(11);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.text(questionLines, margin, y + 1);
        y += questionHeight + 4;

        // Draw Options
        if (q.options && q.options.length > 0) {
          doc.setFontSize(10);
          doc.setTextColor(51, 65, 85);
          doc.setFont('helvetica', 'normal');
          q.options.forEach((opt, idx) => {
            const optLines = optionsLines[idx];
            doc.text(optLines, margin + 5, y);
            y += optLines.length * 5 + 2;
          });
        }

        // Draw Solution
        if (solutionLines.length > 0) {
          y += 2;
          doc.setFontSize(9);
          doc.setTextColor(71, 85, 105);
          doc.setFont('helvetica', 'italic');
          doc.text(solutionLines, margin + 5, y);
          y += solutionLines.length * 4.5 + 4;
        }

        // Draw Metadata
        if (yearText || q.exam || q.subject) {
          doc.setFontSize(8);
          doc.setTextColor(148, 163, 184);
          doc.setFont('helvetica', 'normal');
          const metaText = [q.exam, q.subject, yearText].filter(Boolean).join(' | ');
          doc.text(`Source: ${metaText}`, margin, y);
          y += 6;
        }

        y += 10; // Space between questions
      }

      // Add Answer Key on a NEW PAGE if it's substantial
      if (answers.length > 0) {
        doc.addPage();
        currentPage++;
        addHeader(currentPage);
        y = 30;

        // Answer Key Header
        doc.setFillColor(15, 23, 42);
        doc.roundedRect(margin, y, pageWidth - 2 * margin, 15, 2, 2, 'F');
        doc.setFontSize(14);
        doc.setTextColor(0, 240, 255);
        doc.setFont('helvetica', 'bold');
        doc.text('ANSWER KEY', pageWidth / 2, y + 10, { align: 'center' });
        y += 25;

        // Answer Key Grid
        doc.setFontSize(10);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');

        const cols = 5;
        const colWidth = (pageWidth - 2 * margin) / cols;
        const rowHeight = 10;
        
        for (let i = 0; i < answers.length; i++) {
          if (y > pageHeight - 25) {
            doc.addPage();
            currentPage++;
            addHeader(currentPage);
            y = 30;
          }

          const col = i % cols;
          const row = Math.floor(i / cols);
          
          let ansText = answers[i].answer;
          if (ansText.length > 15) {
             ansText = ansText.substring(0, 12) + '...';
          }
          
          // Draw a small box for each answer
          doc.setDrawColor(226, 232, 240);
          doc.setFillColor(248, 250, 252);
          doc.roundedRect(margin + col * colWidth, y - 6, colWidth - 2, 8, 1, 1, 'FD');
          
          doc.setTextColor(15, 23, 42);
          doc.text(`Q${answers[i].index}: ${ansText}`, margin + col * colWidth + 2, y);
          
          if (col === cols - 1 || i === answers.length - 1) {
            y += rowHeight;
          }
        }
      }

      addFooter();
      // Add footer to all pages
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        addFooter();
      }

      doc.save(`${title.replace(/\s+/g, '_')}_Questions.pdf`);
    } catch (error) {
      console.error('Export failed:', error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <button
      onClick={exportToPDF}
      disabled={isExporting}
      className={className || "flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-[#00F0FF] to-[#B026FF] text-white font-bold hover:shadow-[0_0_20px_rgba(0,240,255,0.4)] transition-all disabled:opacity-50 disabled:cursor-not-allowed"}
    >
      {isExporting ? (
        <>
          <Loader2 className="w-5 h-5 animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <Download className="w-5 h-5" />
          Download PDF (High Quality)
        </>
      )}
    </button>
  );
};
